x-common:
  - &application_user eventsadmin
  - &application_password eventsadmin

name: wm-events

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        REQ_FILE: requirements-dev.txt
    ports:
      - "8000:8000"
    environment:
      # Comment out MOCK_USER to test a "real" keycloak workflow
      MOCK_USER: true
      AUTH_ENVIRONMENT: LOCAL
      S3_ENDPOINT_URL: http://minio:9000
      SQS_ENDPOINT_URL: http://elasticmq:9324
      AWS_ACCESS_KEY_ID: eventsadmin
      AWS_SECRET_ACCESS_KEY: eventsadmin
      AWS_DEFAULT_REGION: us-gov-west-1
      APP_KEY: localdevtoken
      AUTH_HOST: http://traefik/auth
      AUTH_REALM: cwms
      AUTH_CLIENT_IDS: cwms-batch-airflow-swt
      CDA_API_ROOT: http://traefik/cwms-data/
      DEFAULT_JOB_RUNNER: docker-local
      PGUSER: *application_user
      PGPASSWORD: *application_password
      PGDATABASE: postgres
      PGHOST: db
      S3_BUCKET: wm-event-manager-local
      WM_WEB_INTERNAL_S3_BUCKET: wm-web-internal-local
      WM_WEB_PUBLIC_S3_BUCKET: wm-web-public-local
    volumes:
      - ./cwms_batch_events:/code/cwms_batch_events
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - minio
      - db
      - elasticmq
    command: >
      uvicorn cwms_batch_events.api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - cwms

  dispatcher:
    build:
      context: .
      dockerfile: infra/dispatcher/Dockerfile
    depends_on:
      - elasticmq
      - db
    environment:
      AWS_ACCESS_KEY_ID: eventsadmin
      AWS_SECRET_ACCESS_KEY: eventsadmin
      AWS_REGION: us-gov-west-1
      APP_KEY: localdevtoken
      BATCH_EVENTS_API_ROOT: http://api:8000
      BATCH_EVENTS_INTERNAL_TOKEN: localdevtoken
      PGUSER: *application_user
      PGPASSWORD: *application_password
      PGDATABASE: postgres
      PGHOST: db
      QUEUE_URL: http://elasticmq:9324/000000000000/cwms-batch-events
      S3_BUCKET: wm-event-manager-local
      S3_ENDPOINT_URL: http://minio:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cwms


  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - '9324:9324'
      - '9325:9325'
    restart: always
    volumes:
      - ./infra/elasticmq/elasticmq.conf:/opt/elasticmq.conf
    networks:
      - cwms

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=eventsadmin
      - MINIO_ROOT_PASSWORD=eventsadmin
    command: server /data --console-address ":9001"
    networks:
      - cwms

  minio_bootstrap:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to start...';
      until /usr/bin/mc alias set minio http://minio:9000 eventsadmin eventsadmin; do
        echo 'MinIO not ready yet, retrying in 2s...';
        sleep 2;
      done;
      echo 'MinIO is ready. Creating buckets...';
      /usr/bin/mc config host add minio http://minio:9000 eventsadmin eventsadmin;
      /usr/bin/mc mb minio/wm-event-manager-local minio/wm-web-internal-local minio/wm-web-public-local;
      /usr/bin/mc policy set public minio/wm-event-manager-local minio/wm-web-internal-local minio/wm-web-public-local;
      exit 0;
      "
    networks:
      - cwms

  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
    networks:
      - cwms

  flyway:
    platform: linux/amd64
    build:
      context: ./infra/migration
    restart: on-failure
    environment:
      FLYWAY_CLEAN_DISABLED: true
      FLYWAY_PASSWORD: postgres
      FLYWAY_DEFAULT_SCHEMA: wm_events_schema
      FLYWAY_URL: jdbc:postgresql://db:5432/postgres
      FLYWAY_USER: postgres
      FLYWAY_VALIDATE_MIGRATION_NAMING: true
      FLYWAY_OUT_OF_ORDER: true
      FLYWAY_PLACEHOLDERS_APP_USER: *application_user
      FLYWAY_PLACEHOLDERS_APP_PASSWORD: *application_password
    volumes:
      - ./infra/migration/local:/flyway/sql/local
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cwms

volumes:
  minio-data:

networks:
  cwms:
    external: true
