/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ScriptsManagerRouteImport } from './routes/scripts-manager'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as AboutVersionRouteImport } from './routes/about_.version'
import { Route as AboutOnboardingRouteImport } from './routes/about_.onboarding'
import { Route as AboutControlsRouteImport } from './routes/about_.controls'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsManagerRoute = ScriptsManagerRouteImport.update({
  id: '/scripts-manager',
  path: '/scripts-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVersionRoute = AboutVersionRouteImport.update({
  id: '/about_/version',
  path: '/about/version',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOnboardingRoute = AboutOnboardingRouteImport.update({
  id: '/about_/onboarding',
  path: '/about/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutControlsRoute = AboutControlsRouteImport.update({
  id: '/about_/controls',
  path: '/about/controls',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scripts-manager': typeof ScriptsManagerRoute
  '/submit': typeof SubmitRoute
  '/about/controls': typeof AboutControlsRoute
  '/about/onboarding': typeof AboutOnboardingRoute
  '/about/version': typeof AboutVersionRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scripts-manager': typeof ScriptsManagerRoute
  '/submit': typeof SubmitRoute
  '/about/controls': typeof AboutControlsRoute
  '/about/onboarding': typeof AboutOnboardingRoute
  '/about/version': typeof AboutVersionRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scripts-manager': typeof ScriptsManagerRoute
  '/submit': typeof SubmitRoute
  '/about_/controls': typeof AboutControlsRoute
  '/about_/onboarding': typeof AboutOnboardingRoute
  '/about_/version': typeof AboutVersionRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/scripts-manager'
    | '/submit'
    | '/about/controls'
    | '/about/onboarding'
    | '/about/version'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/scripts-manager'
    | '/submit'
    | '/about/controls'
    | '/about/onboarding'
    | '/about/version'
    | '/jobs/$jobId'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/scripts-manager'
    | '/submit'
    | '/about_/controls'
    | '/about_/onboarding'
    | '/about_/version'
    | '/jobs/$jobId'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ScriptsManagerRoute: typeof ScriptsManagerRoute
  SubmitRoute: typeof SubmitRoute
  AboutControlsRoute: typeof AboutControlsRoute
  AboutOnboardingRoute: typeof AboutOnboardingRoute
  AboutVersionRoute: typeof AboutVersionRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts-manager': {
      id: '/scripts-manager'
      path: '/scripts-manager'
      fullPath: '/scripts-manager'
      preLoaderRoute: typeof ScriptsManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/version': {
      id: '/about_/version'
      path: '/about/version'
      fullPath: '/about/version'
      preLoaderRoute: typeof AboutVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/onboarding': {
      id: '/about_/onboarding'
      path: '/about/onboarding'
      fullPath: '/about/onboarding'
      preLoaderRoute: typeof AboutOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/controls': {
      id: '/about_/controls'
      path: '/about/controls'
      fullPath: '/about/controls'
      preLoaderRoute: typeof AboutControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ScriptsManagerRoute: ScriptsManagerRoute,
  SubmitRoute: SubmitRoute,
  AboutControlsRoute: AboutControlsRoute,
  AboutOnboardingRoute: AboutOnboardingRoute,
  AboutVersionRoute: AboutVersionRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
