ARG BUILDER=ghcr.io/cwbi-apps/flyway
ARG BUILDER_TAG=13.5.0
ARG HTTP_CORE_VERSION=5.4.3
ARG HTTP_CORE_SHA256=18bfbbabb478dfb67f31aeaf428c387f3c3df654582e1309f708ee1f3086830a
ARG HTTP_CORE_H2_SHA256=c7db7026b8e2dea39132b04a6069f6671e2858309b20a146ec5c7dd6ed73a0b6
ARG HTTP_CLIENT_VERSION=5.6.3
ARG HTTP_CLIENT_SHA256=80712ff129210d7c73d9fcc1195cbee5c3c34744965c7a05ea107b3648922f18
ARG NETTY_CODEC_HTTP_VERSION=4.2.17.Final
ARG NETTY_CODEC_HTTP_SHA256=a5bde91ac82ab90579df6559c0bd7ea6ae37460e3f18116ab4122194283b3669

FROM alpine:3.22 AS httpcore

ARG HTTP_CORE_VERSION
ARG HTTP_CORE_SHA256
ARG HTTP_CORE_H2_SHA256
ARG HTTP_CLIENT_VERSION
ARG HTTP_CLIENT_SHA256
ARG NETTY_CODEC_HTTP_VERSION
ARG NETTY_CODEC_HTTP_SHA256

RUN wget -q -O /tmp/httpcore5.jar \
      "https://repo.maven.apache.org/maven2/org/apache/httpcomponents/core5/httpcore5/${HTTP_CORE_VERSION}/httpcore5-${HTTP_CORE_VERSION}.jar" \
 && wget -q -O /tmp/httpcore5-h2.jar \
      "https://repo.maven.apache.org/maven2/org/apache/httpcomponents/core5/httpcore5-h2/${HTTP_CORE_VERSION}/httpcore5-h2-${HTTP_CORE_VERSION}.jar" \
 && wget -q -O /tmp/httpclient5.jar \
      "https://repo.maven.apache.org/maven2/org/apache/httpcomponents/client5/httpclient5/${HTTP_CLIENT_VERSION}/httpclient5-${HTTP_CLIENT_VERSION}.jar" \
 && wget -q -O /tmp/netty-codec-http.jar \
      "https://repo.maven.apache.org/maven2/io/netty/netty-codec-http/${NETTY_CODEC_HTTP_VERSION}/netty-codec-http-${NETTY_CODEC_HTTP_VERSION}.jar" \
 && echo "${HTTP_CORE_SHA256}  /tmp/httpcore5.jar" | sha256sum -c - \
 && echo "${HTTP_CORE_H2_SHA256}  /tmp/httpcore5-h2.jar" | sha256sum -c - \
 && echo "${HTTP_CLIENT_SHA256}  /tmp/httpclient5.jar" | sha256sum -c - \
 && echo "${NETTY_CODEC_HTTP_SHA256}  /tmp/netty-codec-http.jar" | sha256sum -c -

# *~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~
# FROM builder
# *~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~
FROM ${BUILDER}:${BUILDER_TAG} AS builder

ARG HTTP_CORE_VERSION
ARG HTTP_CORE_SHA256
ARG HTTP_CORE_H2_SHA256
ARG HTTP_CLIENT_VERSION
ARG NETTY_CODEC_HTTP_VERSION

COPY --from=httpcore /tmp/httpcore5.jar /tmp/httpcore5.jar
COPY --from=httpcore /tmp/httpcore5-h2.jar /tmp/httpcore5-h2.jar
COPY --from=httpcore /tmp/httpclient5.jar /tmp/httpclient5.jar
COPY --from=httpcore /tmp/netty-codec-http.jar /tmp/netty-codec-http.jar

RUN rm -f /flyway/drivers/cassandra/httpcore5-*.jar \
 && rm -f /flyway/drivers/cassandra/httpclient5-*.jar \
 && rm -f /flyway/lib/netty/netty-codec-http-[0-9]*.jar \
 && mv /tmp/httpcore5.jar "/flyway/drivers/cassandra/httpcore5-${HTTP_CORE_VERSION}.jar" \
 && mv /tmp/httpcore5-h2.jar "/flyway/drivers/cassandra/httpcore5-h2-${HTTP_CORE_VERSION}.jar" \
 && mv /tmp/httpclient5.jar "/flyway/drivers/cassandra/httpclient5-${HTTP_CLIENT_VERSION}.jar" \
 && mv /tmp/netty-codec-http.jar "/flyway/lib/netty/netty-codec-http-${NETTY_CODEC_HTTP_VERSION}.jar"

# env vars for FLYWAY
ENV FLYWAY_EDITION=community
ENV FLYWAY_LOCATIONS=filesystem:/flyway/sql

# get the main migration files
COPY ./main /flyway/sql/main

ENTRYPOINT [ "flyway" ]

CMD [ "-connectRetries=60", "migrate" ]
