from typing import Any, Protocol
from uuid import UUID

from cwms_batch_events.core.models import JobRecord, JobStatus, ScriptRunRequest


class JobDatabase(Protocol):
    def create_job(self, payload: ScriptRunRequest, user_id: str) -> JobRecord: ...
    def get_job_by_external_id(self, ext_job_id: str) -> JobRecord | None: ...
    def get_job_by_id(self, job_id: UUID) -> JobRecord | None: ...
    def get_jobs_for_user(self, user_id: str) -> list[JobRecord]: ...
    def update_job_field(self, job_id: UUID, key: str, value: Any) -> None: ...
    def update_job_status(self, job_id: UUID, status: JobStatus) -> None: ...
